# Generated by Django 5.2 on 2025-10-26 04:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_jenis_kelamin_customuser_kota_kab_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='jenis_kelamin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='kota_kab',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='no_ktp',
        ),
        migrations.AddField(
            model_name='customuser',
            name='commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('agent', 'Agent'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
