# Generated by Django 5.2 on 2025-10-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_commission_percent_customuser_komisi_agent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='komisi_agent',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lokasi',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('agent', 'Agent'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
