# Generated by Django 5.2.7 on 2025-10-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_komisi_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lokasi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
