# Generated by Django 5.2 on 2025-11-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_promo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='code',
        ),
        migrations.AddField(
            model_name='promo',
            name='periode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
