# Generated by Django 5.2 on 2025-11-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_promo_code_promo_periode'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
