# Generated by Django 5.2.7 on 2025-11-15 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_promo_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='promo',
            name='code',
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=120)),
                ('destination', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('capacity', models.PositiveIntegerField(default=28)),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('inactive', 'Tidak Aktif'), ('canceled', 'Dibatalkan')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='accounts.bus')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_id', models.CharField(max_length=4)),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(default='paid', max_length=30)),
                ('bought_by', models.CharField(default='user', max_length=10)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='accounts.schedule')),
            ],
            options={
                'unique_together': {('schedule', 'seat_id')},
            },
        ),
    ]
