# Generated by Django 5.2 on 2025-11-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_bus_remove_promo_code_schedule_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='is_sleeper',
            field=models.BooleanField(default=False),
        ),
    ]
