# Generated by Django 5.2 on 2025-11-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_bus_is_sleeper'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='arrival_destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='arrival_origin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='is_sleeper',
            field=models.BooleanField(default=True),
        ),
    ]
