# Generated by Django 5.2.7 on 2026-02-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_agentcommission_commissionperiod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionperiod',
            name='total_commission',
        ),
        migrations.AddField(
            model_name='commissionperiod',
            name='bukti_transfer',
            field=models.ImageField(blank=True, null=True, upload_to='transfer_agen/'),
        ),
        migrations.AddField(
            model_name='commissionperiod',
            name='periode_name',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='commissionperiod',
            name='total_komisi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='commissionperiod',
            name='total_transaksi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='commissionperiod',
            name='status',
            field=models.CharField(choices=[('belum_bayar', 'Belum Bayar'), ('sudah_bayar', 'Sudah Bayar')], default='belum_bayar', max_length=20),
        ),
        migrations.AlterField(
            model_name='commissionperiod',
            name='total_setor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
